(function() {var implementors = {};
implementors["tower_balance"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_balance/choose/struct.TooFew.html\" title=\"struct tower_balance::choose::TooFew\">TooFew</a>",synthetic:false,types:["tower_balance::choose::TooFew"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_balance/load/struct.NoInstrument.html\" title=\"struct tower_balance::load::NoInstrument\">NoInstrument</a>",synthetic:false,types:["tower_balance::load::instrument::NoInstrument"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_balance/load/peak_ewma/struct.Cost.html\" title=\"struct tower_balance::load::peak_ewma::Cost\">Cost</a>",synthetic:false,types:["tower_balance::load::peak_ewma::Cost"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_balance/load/pending_requests/struct.Count.html\" title=\"struct tower_balance::load::pending_requests::Count\">Count</a>",synthetic:false,types:["tower_balance::load::pending_requests::Count"]},];
implementors["tower_buffer"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_buffer/struct.Buffer.html\" title=\"struct tower_buffer::Buffer\">Buffer</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"tower_service/trait.Service.html\" title=\"trait tower_service::Service\">Service</a>,&nbsp;</span>",synthetic:false,types:["tower_buffer::Buffer"]},];
implementors["tower_in_flight_limit"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_in_flight_limit/struct.InFlightLimit.html\" title=\"struct tower_in_flight_limit::InFlightLimit\">InFlightLimit</a>&lt;T&gt;",synthetic:false,types:["tower_in_flight_limit::InFlightLimit"]},];
implementors["tower_mock"] = [{text:"impl&lt;T, U, E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_mock/struct.Mock.html\" title=\"struct tower_mock::Mock\">Mock</a>&lt;T, U, E&gt;",synthetic:false,types:["tower_mock::Mock"]},];
implementors["tower_rate_limit"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"tower_rate_limit/struct.Rate.html\" title=\"struct tower_rate_limit::Rate\">Rate</a>",synthetic:false,types:["tower_rate_limit::Rate"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
